# -*- coding: utf-8 -*-
"""DepressionChatBot - OpenAI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fCemhCxCZ1vc-Gqtr1XD2xi5WJLOk2Mi
"""

!pip install openai
!openai tools fine_tunes.prepare_data -f 'depression.jsonl'

!set OPENAI_API_KEY = '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'

import os

!openai --api-key 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 api fine_tunes.create -t "depression_prepared.jsonl" -m davinci

!openai api completions.create -m davinci:ft-personal-2022-12-18-17-56-01 -

